[package]
name = "Nr8"
version = "0.1.0"
authors = ["Emil Beothy-Elo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
