[package]
name = "thread_matrix"
version = "0.1.0"
authors = ["Emil <s6embeot@uni-bonn.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
